2018-05-31 08:34:26  [ main:0 ] - [ DEBUG ]  Using Log4J as the default logging framework
2018-05-31 08:34:26  [ main:11 ] - [ DEBUG ]  java.nio.Buffer.address: available
2018-05-31 08:34:26  [ main:11 ] - [ DEBUG ]  sun.misc.Unsafe.theUnsafe: available
2018-05-31 08:34:26  [ main:14 ] - [ DEBUG ]  sun.misc.Unsafe.copyMemory: available
2018-05-31 08:34:26  [ main:15 ] - [ DEBUG ]  java.nio.Bits.unaligned: true
2018-05-31 08:34:26  [ main:16 ] - [ DEBUG ]  Platform: Windows
2018-05-31 08:34:26  [ main:17 ] - [ DEBUG ]  Java version: 7
2018-05-31 08:34:26  [ main:17 ] - [ DEBUG ]  -Dio.netty.noUnsafe: false
2018-05-31 08:34:26  [ main:17 ] - [ DEBUG ]  sun.misc.Unsafe: available
2018-05-31 08:34:26  [ main:18 ] - [ DEBUG ]  -Dio.netty.noJavassist: false
2018-05-31 08:34:26  [ main:117 ] - [ DEBUG ]  Javassist: available
2018-05-31 08:34:26  [ main:117 ] - [ DEBUG ]  -Dio.netty.tmpdir: C:\Users\tlju\AppData\Local\Temp (java.io.tmpdir)
2018-05-31 08:34:26  [ main:118 ] - [ DEBUG ]  -Dio.netty.bitMode: 32 (sun.arch.data.model)
2018-05-31 08:34:26  [ main:118 ] - [ DEBUG ]  -Dio.netty.noPreferDirect: false
2018-05-31 08:34:26  [ main:138 ] - [ DEBUG ]  -Dio.netty.leakDetectionLevel: simple
2018-05-31 08:34:26  [ main:160 ] - [ DEBUG ]  -Dio.netty.eventLoopThreads: 8
2018-05-31 08:34:26  [ main:183 ] - [ DEBUG ]  -Dio.netty.noKeySetOptimization: false
2018-05-31 08:34:26  [ main:183 ] - [ DEBUG ]  -Dio.netty.selectorAutoRebuildThreshold: 512
2018-05-31 08:34:26  [ main:301 ] - [ INFO ]  Start to create connection to 10.150.68.133:60001 for channel :10.150.68.133:60001::0.
2018-05-31 08:34:28  [ main:2439 ] - [ DEBUG ]  -Dio.netty.initialSeedUniquifier: 0x3564045bd1b5b82c (took 2114 ms)
2018-05-31 08:34:28  [ main:2502 ] - [ DEBUG ]  -Dio.netty.allocator.type: unpooled
2018-05-31 08:34:28  [ main:2502 ] - [ DEBUG ]  -Dio.netty.threadLocalDirectBufferSize: 65536
2018-05-31 08:34:28  [ NettyTransceiver-eventLoopGroup 1:2525 ] - [ DEBUG ]  Generated: io.netty.util.internal.__matchers__.com.csg.itms.edic.util.protocol.ProtocolPackMatcher
2018-05-31 08:34:29  [ NettyTransceiver-eventLoopGroup 1:3722 ] - [ WARN ]  Channel :10.150.68.133:60001::0 is ungreistered with null from local address :null
2018-05-31 08:34:29  [ main:3723 ] - [ ERROR ]  Exception in get channel :java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.netty.AbstractChannelFactory.get(AbstractChannelFactory.java:96)
	at com.csg.itms.edic.util.netty.NettyTransceiver.getChannel(NettyTransceiver.java:343)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:248)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.authenticate(EDIClient.java:130)
Caused by: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

2018-05-31 08:34:29  [ main:3727 ] - [ ERROR ]  Error happened when call invokeAsync of RPCClient , caused by java.io.IOException: channel is null.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:250)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.authenticate(EDIClient.java:130)

2018-05-31 08:34:29  [ main:3728 ] - [ ERROR ]  Error happened in authenticate process, caused by java.io.IOException: channel is null.
2018-05-31 08:34:29  [ main:3746 ] - [ INFO ]  Start to create connection to 10.150.68.133:60001 for channel :10.150.68.133:60001::0.
2018-05-31 08:34:30  [ NettyTransceiver-eventLoopGroup 2:4915 ] - [ WARN ]  Channel :10.150.68.133:60001::0 is ungreistered with null from local address :null
2018-05-31 08:34:30  [ main:4916 ] - [ ERROR ]  Exception in get channel :java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.netty.AbstractChannelFactory.get(AbstractChannelFactory.java:96)
	at com.csg.itms.edic.util.netty.NettyTransceiver.getChannel(NettyTransceiver.java:343)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:280)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)
Caused by: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

2018-05-31 08:34:30  [ main:4917 ] - [ ERROR ]  There is no netty channel can be send the message.
2018-05-31 08:34:30  [ main:4917 ] - [ ERROR ]  Error happened when call invokeAsync of RPCClient , caused by java.io.IOException: There is no netty channel can be send the message.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeToChannel(NettyTransceiver.java:294)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:286)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)

2018-05-31 08:34:30  [ main:4918 ] - [ ERROR ]  Error happened in sendMessage, caused by java.util.concurrent.ExecutionException: java.io.IOException: There is no netty channel can be send the message.
	at org.apache.avro.ipc.CallFuture.get(CallFuture.java:118)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:80)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)
Caused by: java.io.IOException: There is no netty channel can be send the message.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeToChannel(NettyTransceiver.java:294)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:286)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	... 1 more

2018-05-31 08:34:56  [ EDIClient Scheduler 1:30248 ] - [ INFO ]  No¡£=1 SubjectName=SOA2NARIAlertSend   Current RPS=0   Avg RPS=0  Success Request=0  Total Request=1  Failure Request=1
2018-05-31 08:34:56  [ pool-1-thread-1:30396 ] - [ ERROR ]  Error happened in CallbackTimeoutDecorate, for the -2147483648's data package.
2018-05-31 08:34:59  [ pool-1-thread-1:33796 ] - [ ERROR ]  Error happened in CallbackTimeoutDecorate, for the -2147483647's data package.
